# Generated by Django 3.1.2 on 2020-11-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=15)),
                ('edad', models.CharField(max_length=15)),
                ('Tipo_baldosa', models.CharField(max_length=80)),
                ('Tipo_Salpicadero', models.CharField(max_length=80)),
                ('Tipo_Baño', models.CharField(max_length=100)),
                ('Tipo_Sala', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('picture', models.CharField(max_length=50)),
            ],
        ),
    ]
