# Generated by Django 3.1.2 on 2020-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_facebook',
            name='picture',
            field=models.CharField(max_length=100),
        ),
    ]
