# Generated by Django 3.1.2 on 2020-11-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0003_auto_20201120_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlFormulario', models.CharField(max_length=200, unique=True)),
                ('urlRespuestas', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
