# Generated by Django 3.1.2 on 2020-11-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0004_formularios'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='nombreFormulario',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
