# Generated by Django 3.1.2 on 2020-11-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0005_formularios_nombreformulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='descripcion',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
