# Generated by Django 3.1.2 on 2020-11-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0006_formularios_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularios',
            name='descripcion',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
