# Generated by Django 3.1.2 on 2020-11-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0009_auto_20201126_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultados',
            old_name='emailSocial',
            new_name='Usuario',
        ),
    ]
