# Generated by Django 3.1.2 on 2020-11-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0011_auto_20201126_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularios',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
