# Generated by Django 3.1.2 on 2020-11-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0012_formularios_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultados',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Facebook_API.user_facebook'),
            preserve_default=False,
        ),
    ]
