# Generated by Django 3.1.2 on 2020-11-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0014_auto_20201127_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultados',
            old_name='Usuario_id',
            new_name='Usuario',
        ),
    ]
