# Generated by Django 3.1.2 on 2020-12-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0015_auto_20201127_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='Timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
