# Generated by Django 3.1.2 on 2020-12-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facebook_API', '0016_auto_20201204_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='Tipo_Baño',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='Tipo_Sala',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='Tipo_Salpicadero',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='Tipo_baldosa',
            field=models.CharField(max_length=255),
        ),
    ]
